#ifndef EDITORFRAMEWORK_GLOBAL_H
#define EDITORFRAMEWORK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EDITORFRAMEWORK_LIBRARY)
#  define EDITORFRAMEWORKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EDITORFRAMEWORKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EDITORFRAMEWORK_GLOBAL_H
